$$h_t = f(x_t + h_{t-1})$$

$W_{xh}$ = U, $W_{hh}$ = W, $b_h$: bias

$\sigma$: sigmoid, activation function

$s_t$ == $h_t$, h = hidden layer, s = state

State at specific time is the output of hidden layer

$$h_t = \sigma(Ux_t + Wh_{t-1} + b_h)$$

In [1]:
import numpy as np

import tensorflow as tf

In [2]:
inputs = np.random.random(size = (32,28,32)).astype(np.float32)  # random numbers between 0 and 1

32 samples, 28 time series
$$x_1,x_2,……x_t,……x_{28}$$  
each time series has 32 characteristics

![](https://pic2.zhimg.com/80/v2-b0175ebd3419f9a11a3d0d8b00e28675_1440w.jpg)

In [3]:
rnn = tf.keras.layers.SimpleRNN(16, # 16 neurons
                                    activation = tf.nn.tanh,
                                    return_sequences = True,# return data at every time step
                                    return_state = True) # return the last result
sequences,state = rnn(inputs) # sequences: results in the process, state: result

# last output
print(sequences.shape,state.shape)

(32, 28, 16) (32, 16)


In [4]:
sequences[:,-1][:2]

<tf.Tensor: shape=(2, 16), dtype=float32, numpy=
array([[-0.25664946, -0.7416231 , -0.26449808, -0.01215898,  0.66506153,
        -0.38297573,  0.70326364,  0.5076195 , -0.30021602,  0.23183618,
         0.0272775 ,  0.88940847, -0.95251817, -0.83762103,  0.8778303 ,
        -0.06520741],
       [-0.27784014, -0.9176324 ,  0.04051448,  0.50965625,  0.60097754,
         0.2909992 ,  0.81932956, -0.5233518 , -0.24118832,  0.566046  ,
        -0.10446535,  0.877389  ,  0.00388835, -0.25564942,  0.733724  ,
        -0.7329151 ]], dtype=float32)>

In [55]:
state[:2]

<tf.Tensor: shape=(2, 16), dtype=float32, numpy=
array([[ 0.4970446 , -0.8579154 ,  0.72851974,  0.40602782,  0.53389853,
        -0.80420357,  0.7127699 ,  0.92607135,  0.7152646 , -0.5357565 ,
         0.24980713,  0.9459391 ,  0.05063101,  0.14126149,  0.8799345 ,
        -0.7283145 ],
       [-0.45538002, -0.6366028 ,  0.49387133,  0.67291313, -0.31530312,
        -0.5781308 ,  0.64037615,  0.44671962,  0.6169176 , -0.43583414,
         0.66903955,  0.8196184 ,  0.27696374,  0.35599178,  0.73411894,
        -0.51005393]], dtype=float32)>

In [6]:
# the result at t1
sequences[:,0,:][:2]

<tf.Tensor: shape=(2, 16), dtype=float32, numpy=
array([[ 0.52839065, -0.86626714,  0.60178876, -0.07501654,  0.81102765,
        -0.55168635,  0.37148014, -0.49405664, -0.87643147, -0.41709647,
        -0.52287436,  0.6241939 , -0.90340096, -0.7209769 ,  0.71031255,
        -0.6986853 ],
       [ 0.372018  , -0.91004   ,  0.68763226, -0.6376716 ,  0.55435956,
         0.14166729, -0.50071543, -0.52447593, -0.9242554 , -0.6369396 ,
        -0.20806749,  0.6788409 , -0.9055065 ,  0.12999529,  0.64272845,
         0.02665365]], dtype=float32)>

### Manual Calculation

In [8]:
v = rnn.variables
U = v[0].numpy()
W = v[1].numpy()
V = v[2].numpy()

$$S_t = f(UX_t + WS_{t-1}) = UX_t + WS_{t-1}$$

f is the activation function (tanh, as metioned above)

![](https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=2927054899,245498266&fm=26&gp=0.jpg)

### Core codes of RNN

In [9]:
result = []
for i in range(28):
    if i ==0:  # S0 = 0
        result.append(tf.nn.tanh(inputs[:,0].dot(U)).numpy())
    else:
        result.append(tf.nn.tanh(inputs[:,i].dot(U) + result[i-1].dot(W)).numpy())
result = np.asarray(result)
result = np.transpose(result,axes = [1,0,2])  # transpose the first dimensin and the second one
result.shape

(32, 28, 16)

In [10]:
result[:,-1][:2]

array([[-0.25664946, -0.7416231 , -0.26449808, -0.01215898,  0.66506153,
        -0.38297573,  0.70326364,  0.5076195 , -0.30021602,  0.23183618,
         0.0272775 ,  0.88940847, -0.95251817, -0.83762103,  0.8778303 ,
        -0.06520741],
       [-0.27784014, -0.9176324 ,  0.04051448,  0.50965625,  0.60097754,
         0.2909992 ,  0.81932956, -0.5233518 , -0.24118832,  0.566046  ,
        -0.10446535,  0.877389  ,  0.00388835, -0.25564942,  0.733724  ,
        -0.7329151 ]], dtype=float32)

In [11]:
sequences[:,-1][:2]

<tf.Tensor: shape=(2, 16), dtype=float32, numpy=
array([[-0.25664946, -0.7416231 , -0.26449808, -0.01215898,  0.66506153,
        -0.38297573,  0.70326364,  0.5076195 , -0.30021602,  0.23183618,
         0.0272775 ,  0.88940847, -0.95251817, -0.83762103,  0.8778303 ,
        -0.06520741],
       [-0.27784014, -0.9176324 ,  0.04051448,  0.50965625,  0.60097754,
         0.2909992 ,  0.81932956, -0.5233518 , -0.24118832,  0.566046  ,
        -0.10446535,  0.877389  ,  0.00388835, -0.25564942,  0.733724  ,
        -0.7329151 ]], dtype=float32)>